# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import push_service_pb2 as push__service__pb2


class PushingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/main.Pushing/Ping',
        request_serializer=push__service__pb2.PingRequest.SerializeToString,
        response_deserializer=push__service__pb2.PongResponse.FromString,
        )
    self.PushStream = channel.stream_stream(
        '/main.Pushing/PushStream',
        request_serializer=push__service__pb2.Push.SerializeToString,
        response_deserializer=push__service__pb2.Response.FromString,
        )


class PushingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PushStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PushingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=push__service__pb2.PingRequest.FromString,
          response_serializer=push__service__pb2.PongResponse.SerializeToString,
      ),
      'PushStream': grpc.stream_stream_rpc_method_handler(
          servicer.PushStream,
          request_deserializer=push__service__pb2.Push.FromString,
          response_serializer=push__service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'main.Pushing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
